# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kvtide/v1/core.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'kvtide/v1/core.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from vendor.daotl.protoc_gen_go_enums import ext_pb2 as vendor_dot_daotl_dot_protoc__gen__go__enums_dot_ext__pb2
from vendor.daotl.protoc_gen_go_string_consts import ext_pb2 as vendor_dot_daotl_dot_protoc__gen__go__string__consts_dot_ext__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14kvtide/v1/core.proto\x12\tkvtide.v1\x1a*vendor/daotl/protoc-gen-go-enums/ext.proto\x1a\x32vendor/daotl/protoc-gen-go-string-consts/ext.proto\"J\n\x05Usage\x12\x14\n\x0cinput_tokens\x18\x01 \x01(\r\x12\x15\n\routput_tokens\x18\x02 \x01(\r\x12\x14\n\x0ctotal_tokens\x18\x03 \x01(\r\"Y\n\x06Timing\x12\x10\n\x08queue_ms\x18\x01 \x01(\r\x12\x15\n\rbatch_wait_ms\x18\x02 \x01(\r\x12\x14\n\x0c\x65xecution_ms\x18\x03 \x01(\r\x12\x10\n\x08total_ms\x18\x04 \x01(\r\"1\n\tBatchInfo\x12\x10\n\x08\x62\x61tch_id\x18\x01 \x01(\t\x12\x12\n\nbatch_size\x18\x02 \x01(\r*\xe3\x01\n\x0c\x46inishReason\x12\x1d\n\x19\x46INISH_REASON_UNSPECIFIED\x10\x00\x12\x16\n\x12\x46INISH_REASON_STOP\x10\x01\x12\x18\n\x14\x46INISH_REASON_LENGTH\x10\x02\x12\x19\n\x15\x46INISH_REASON_TIMEOUT\x10\x03\x12\x17\n\x13\x46INISH_REASON_ERROR\x10\x04\x1aN\xa0\xe3,\x01\xaa\xe3,\rFinishReason_\xb0\xe3,\x01\xca\xe3,\x03Str\xd2\xe3,\x0e\x46INISH_REASON_\xda\xe3,\x03\x46R_\xca\xe4,\rFinishReason_\xd0\xe4,\x01*\x81\x01\n\tWorkPhase\x12\x16\n\x12WORK_PHASE_PREFILL\x10\x00\x12\x15\n\x11WORK_PHASE_DECODE\x10\x01\x1a\x45\xa0\xe3,\x01\xaa\xe3,\nWorkPhase_\xb0\xe3,\x01\xca\xe3,\x03Str\xd2\xe3,\x0bWORK_PHASE_\xda\xe3,\x03WR_\xca\xe4,\nWorkPhase_\xd0\xe4,\x01*\x8f\x02\n\tEventType\x12\x1c\n\x18\x45VENT_TYPE_PREFILL_CHUNK\x10\x00\x12\x1f\n\x1b\x45VENT_TYPE_PREFILL_FINISHED\x10\x01\x12\x1b\n\x17\x45VENT_TYPE_DECODE_CHUNK\x10\x02\x12\x1f\n\x1b\x45VENT_TYPE_REQUEST_FINISHED\x10\x03\x12\x1d\n\x19\x45VENT_TYPE_REQUEST_FAILED\x10\x04\x12\x1f\n\x1b\x45VENT_TYPE_REQUEST_CANCELED\x10\x05\x1a\x45\xa0\xe3,\x01\xaa\xe3,\nEventType_\xb0\xe3,\x01\xca\xe3,\x03Str\xd2\xe3,\x0b\x45VENT_TYPE_\xda\xe3,\x03\x45T_\xca\xe4,\nEventType_\xd0\xe4,\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kvtide.v1.core_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FINISHREASON']._loaded_options = None
  _globals['_FINISHREASON']._serialized_options = b'\240\343,\001\252\343,\rFinishReason_\260\343,\001\312\343,\003Str\322\343,\016FINISH_REASON_\332\343,\003FR_\312\344,\rFinishReason_\320\344,\001'
  _globals['_WORKPHASE']._loaded_options = None
  _globals['_WORKPHASE']._serialized_options = b'\240\343,\001\252\343,\nWorkPhase_\260\343,\001\312\343,\003Str\322\343,\013WORK_PHASE_\332\343,\003WR_\312\344,\nWorkPhase_\320\344,\001'
  _globals['_EVENTTYPE']._loaded_options = None
  _globals['_EVENTTYPE']._serialized_options = b'\240\343,\001\252\343,\nEventType_\260\343,\001\312\343,\003Str\322\343,\013EVENT_TYPE_\332\343,\003ET_\312\344,\nEventType_\320\344,\001'
  _globals['_FINISHREASON']._serialized_start=350
  _globals['_FINISHREASON']._serialized_end=577
  _globals['_WORKPHASE']._serialized_start=580
  _globals['_WORKPHASE']._serialized_end=709
  _globals['_EVENTTYPE']._serialized_start=712
  _globals['_EVENTTYPE']._serialized_end=983
  _globals['_USAGE']._serialized_start=131
  _globals['_USAGE']._serialized_end=205
  _globals['_TIMING']._serialized_start=207
  _globals['_TIMING']._serialized_end=296
  _globals['_BATCHINFO']._serialized_start=298
  _globals['_BATCHINFO']._serialized_end=347
# @@protoc_insertion_point(module_scope)
