# Generated from kvtide/v1/executor.proto. DO NOT EDIT.
# Generated by protoc-gen-connectrpc-py v0.11.1 with parameter "protobuf=google".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Protocol, TYPE_CHECKING

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.compat import google_protobuf_binary_codec, google_protobuf_codecs
from connectrpc.compression.gzip import GzipCompression
from connectrpc.errors import ConnectError
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.protocol import ProtocolType
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
from pyqwest import Client, SyncClient

from .executor_pb2 import ExecuteBatchRequest, ExecuteBatchResponse, GetRuntimeRequest, GetRuntimeResponse, PushKVRequest, PushKVResponse, ReleaseBlocksRequest, ReleaseBlocksResponse

if TYPE_CHECKING:
    from collections.abc import AsyncGenerator, Iterable, Mapping

    from connectrpc.codec import Codec
    from connectrpc.compression import Compression
    from connectrpc.interceptor import Interceptor, InterceptorSync
    from connectrpc.request import Headers, RequestContext



_DEFAULT_CODECS = google_protobuf_codecs()
_PROTO_BINARY_CODEC = google_protobuf_binary_codec()
_GZIP_COMPRESSION = GzipCompression()

class ExecutorService(Protocol):
    async def get_runtime(self, request: GetRuntimeRequest, ctx: RequestContext[GetRuntimeRequest, GetRuntimeResponse]) -> GetRuntimeResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def execute_batch(self, request: ExecuteBatchRequest, ctx: RequestContext[ExecuteBatchRequest, ExecuteBatchResponse]) -> ExecuteBatchResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def release_blocks(self, request: ReleaseBlocksRequest, ctx: RequestContext[ReleaseBlocksRequest, ReleaseBlocksResponse]) -> ReleaseBlocksResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def push_kv(self, request: PushKVRequest, ctx: RequestContext[PushKVRequest, PushKVResponse]) -> PushKVResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class ExecutorServiceASGIApplication(ConnectASGIApplication[ExecutorService]):
    def __init__(
        self,
        service: ExecutorService | AsyncGenerator[ExecutorService],
        *,
        interceptors: Iterable[Interceptor] = (),
        read_max_bytes: int | None = None,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = _DEFAULT_CODECS,
    ) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/kvtide.v1.ExecutorService/GetRuntime": Endpoint.unary(
                    method=MethodInfo(
                        name="GetRuntime",
                        service_name="kvtide.v1.ExecutorService",
                        input=GetRuntimeRequest,
                        output=GetRuntimeResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_runtime,
                ),
                "/kvtide.v1.ExecutorService/ExecuteBatch": Endpoint.unary(
                    method=MethodInfo(
                        name="ExecuteBatch",
                        service_name="kvtide.v1.ExecutorService",
                        input=ExecuteBatchRequest,
                        output=ExecuteBatchResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.execute_batch,
                ),
                "/kvtide.v1.ExecutorService/ReleaseBlocks": Endpoint.unary(
                    method=MethodInfo(
                        name="ReleaseBlocks",
                        service_name="kvtide.v1.ExecutorService",
                        input=ReleaseBlocksRequest,
                        output=ReleaseBlocksResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.release_blocks,
                ),
                "/kvtide.v1.ExecutorService/PushKV": Endpoint.unary(
                    method=MethodInfo(
                        name="PushKV",
                        service_name="kvtide.v1.ExecutorService",
                        input=PushKVRequest,
                        output=PushKVResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.push_kv,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/kvtide.v1.ExecutorService"


class ExecutorServiceClient(ConnectClient):
    def __init__(
        self,
        address: str,
        *,
        codec: Codec | None = _PROTO_BINARY_CODEC,
        protocol: ProtocolType = ProtocolType.CONNECT,
        accept_compression: Iterable[Compression] | None = None,
        send_compression: Compression | None = _GZIP_COMPRESSION,
        timeout_ms: int | None = None,
        read_max_bytes: int | None = None,
        interceptors: Iterable[Interceptor] = (),
        http_client: Client | None = None,
    ) -> None:
        super().__init__(
            address=address,
            codec=codec,
            protocol=protocol,
            accept_compression=accept_compression,
            send_compression=send_compression,
            timeout_ms=timeout_ms,
            read_max_bytes=read_max_bytes,
            interceptors=interceptors,
            http_client=http_client,
        )
    async def get_runtime(
        self,
        request: GetRuntimeRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> GetRuntimeResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetRuntime",
                service_name="kvtide.v1.ExecutorService",
                input=GetRuntimeRequest,
                output=GetRuntimeResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def execute_batch(
        self,
        request: ExecuteBatchRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ExecuteBatchResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ExecuteBatch",
                service_name="kvtide.v1.ExecutorService",
                input=ExecuteBatchRequest,
                output=ExecuteBatchResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def release_blocks(
        self,
        request: ReleaseBlocksRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ReleaseBlocksResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ReleaseBlocks",
                service_name="kvtide.v1.ExecutorService",
                input=ReleaseBlocksRequest,
                output=ReleaseBlocksResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def push_kv(
        self,
        request: PushKVRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> PushKVResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="PushKV",
                service_name="kvtide.v1.ExecutorService",
                input=PushKVRequest,
                output=PushKVResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

class ExecutorServiceSync(Protocol):
    def get_runtime(self, request: GetRuntimeRequest, ctx: RequestContext[GetRuntimeRequest, GetRuntimeResponse]) -> GetRuntimeResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def execute_batch(self, request: ExecuteBatchRequest, ctx: RequestContext[ExecuteBatchRequest, ExecuteBatchResponse]) -> ExecuteBatchResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def release_blocks(self, request: ReleaseBlocksRequest, ctx: RequestContext[ReleaseBlocksRequest, ReleaseBlocksResponse]) -> ReleaseBlocksResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def push_kv(self, request: PushKVRequest, ctx: RequestContext[PushKVRequest, PushKVResponse]) -> PushKVResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class ExecutorServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(
        self,
        service: ExecutorServiceSync,
        interceptors: Iterable[InterceptorSync] = (),
        read_max_bytes: int | None = None,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = _DEFAULT_CODECS,
    ) -> None:
        super().__init__(
            endpoints={
                "/kvtide.v1.ExecutorService/GetRuntime": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetRuntime",
                        service_name="kvtide.v1.ExecutorService",
                        input=GetRuntimeRequest,
                        output=GetRuntimeResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_runtime,
                ),
                "/kvtide.v1.ExecutorService/ExecuteBatch": EndpointSync.unary(
                    method=MethodInfo(
                        name="ExecuteBatch",
                        service_name="kvtide.v1.ExecutorService",
                        input=ExecuteBatchRequest,
                        output=ExecuteBatchResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.execute_batch,
                ),
                "/kvtide.v1.ExecutorService/ReleaseBlocks": EndpointSync.unary(
                    method=MethodInfo(
                        name="ReleaseBlocks",
                        service_name="kvtide.v1.ExecutorService",
                        input=ReleaseBlocksRequest,
                        output=ReleaseBlocksResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.release_blocks,
                ),
                "/kvtide.v1.ExecutorService/PushKV": EndpointSync.unary(
                    method=MethodInfo(
                        name="PushKV",
                        service_name="kvtide.v1.ExecutorService",
                        input=PushKVRequest,
                        output=PushKVResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.push_kv,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/kvtide.v1.ExecutorService"


class ExecutorServiceClientSync(ConnectClientSync):
    def __init__(
        self,
        address: str,
        *,
        codec: Codec | None = _PROTO_BINARY_CODEC,
        protocol: ProtocolType = ProtocolType.CONNECT,
        accept_compression: Iterable[Compression] | None = None,
        send_compression: Compression | None = _GZIP_COMPRESSION,
        timeout_ms: int | None = None,
        read_max_bytes: int | None = None,
        interceptors: Iterable[InterceptorSync] = (),
        http_client: SyncClient | None = None,
    ) -> None:
        super().__init__(
            address=address,
            codec=codec,
            protocol=protocol,
            accept_compression=accept_compression,
            send_compression=send_compression,
            timeout_ms=timeout_ms,
            read_max_bytes=read_max_bytes,
            interceptors=interceptors,
            http_client=http_client,
        )
    def get_runtime(
        self,
        request: GetRuntimeRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> GetRuntimeResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetRuntime",
                service_name="kvtide.v1.ExecutorService",
                input=GetRuntimeRequest,
                output=GetRuntimeResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def execute_batch(
        self,
        request: ExecuteBatchRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ExecuteBatchResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ExecuteBatch",
                service_name="kvtide.v1.ExecutorService",
                input=ExecuteBatchRequest,
                output=ExecuteBatchResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def release_blocks(
        self,
        request: ReleaseBlocksRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ReleaseBlocksResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ReleaseBlocks",
                service_name="kvtide.v1.ExecutorService",
                input=ReleaseBlocksRequest,
                output=ReleaseBlocksResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def push_kv(
        self,
        request: PushKVRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> PushKVResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="PushKV",
                service_name="kvtide.v1.ExecutorService",
                input=PushKVRequest,
                output=PushKVResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
