# Generated from kvtide/v1/service.proto. DO NOT EDIT.
# Generated by protoc-gen-connectrpc-py v0.11.1 with parameter "protobuf=google".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Protocol, TYPE_CHECKING

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.compat import google_protobuf_binary_codec, google_protobuf_codecs
from connectrpc.compression.gzip import GzipCompression
from connectrpc.errors import ConnectError
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.protocol import ProtocolType
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
from pyqwest import Client, SyncClient

from .service_pb2 import GenerateRequest, GenerateResponse, GenerateResponseChunk, GetExecutorsRequest, GetExecutorsResponse, GetRuntimeStatsRequest, GetRuntimeStatsResponse, HealthRequest, HealthResponse

if TYPE_CHECKING:
    from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping

    from connectrpc.codec import Codec
    from connectrpc.compression import Compression
    from connectrpc.interceptor import Interceptor, InterceptorSync
    from connectrpc.request import Headers, RequestContext



_DEFAULT_CODECS = google_protobuf_codecs()
_PROTO_BINARY_CODEC = google_protobuf_binary_codec()
_GZIP_COMPRESSION = GzipCompression()

class InferenceService(Protocol):
    async def generate(self, request: GenerateRequest, ctx: RequestContext[GenerateRequest, GenerateResponse]) -> GenerateResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def generate_stream(self, request: GenerateRequest, ctx: RequestContext[GenerateRequest, GenerateResponseChunk]) -> AsyncIterator[GenerateResponseChunk]:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class InferenceServiceASGIApplication(ConnectASGIApplication[InferenceService]):
    def __init__(
        self,
        service: InferenceService | AsyncGenerator[InferenceService],
        *,
        interceptors: Iterable[Interceptor] = (),
        read_max_bytes: int | None = None,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = _DEFAULT_CODECS,
    ) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/kvtide.v1.InferenceService/Generate": Endpoint.unary(
                    method=MethodInfo(
                        name="Generate",
                        service_name="kvtide.v1.InferenceService",
                        input=GenerateRequest,
                        output=GenerateResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.generate,
                ),
                "/kvtide.v1.InferenceService/GenerateStream": Endpoint.server_stream(
                    method=MethodInfo(
                        name="GenerateStream",
                        service_name="kvtide.v1.InferenceService",
                        input=GenerateRequest,
                        output=GenerateResponseChunk,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.generate_stream,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/kvtide.v1.InferenceService"


class InferenceServiceClient(ConnectClient):
    def __init__(
        self,
        address: str,
        *,
        codec: Codec | None = _PROTO_BINARY_CODEC,
        protocol: ProtocolType = ProtocolType.CONNECT,
        accept_compression: Iterable[Compression] | None = None,
        send_compression: Compression | None = _GZIP_COMPRESSION,
        timeout_ms: int | None = None,
        read_max_bytes: int | None = None,
        interceptors: Iterable[Interceptor] = (),
        http_client: Client | None = None,
    ) -> None:
        super().__init__(
            address=address,
            codec=codec,
            protocol=protocol,
            accept_compression=accept_compression,
            send_compression=send_compression,
            timeout_ms=timeout_ms,
            read_max_bytes=read_max_bytes,
            interceptors=interceptors,
            http_client=http_client,
        )
    async def generate(
        self,
        request: GenerateRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> GenerateResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Generate",
                service_name="kvtide.v1.InferenceService",
                input=GenerateRequest,
                output=GenerateResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def generate_stream(
        self,
        request: GenerateRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> AsyncIterator[GenerateResponseChunk]:
        return self.execute_server_stream(
            request=request,
            method=MethodInfo(
                name="GenerateStream",
                service_name="kvtide.v1.InferenceService",
                input=GenerateRequest,
                output=GenerateResponseChunk,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

class InferenceServiceSync(Protocol):
    def generate(self, request: GenerateRequest, ctx: RequestContext[GenerateRequest, GenerateResponse]) -> GenerateResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def generate_stream(self, request: GenerateRequest, ctx: RequestContext[GenerateRequest, GenerateResponseChunk]) -> Iterator[GenerateResponseChunk]:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class InferenceServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(
        self,
        service: InferenceServiceSync,
        interceptors: Iterable[InterceptorSync] = (),
        read_max_bytes: int | None = None,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = _DEFAULT_CODECS,
    ) -> None:
        super().__init__(
            endpoints={
                "/kvtide.v1.InferenceService/Generate": EndpointSync.unary(
                    method=MethodInfo(
                        name="Generate",
                        service_name="kvtide.v1.InferenceService",
                        input=GenerateRequest,
                        output=GenerateResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.generate,
                ),
                "/kvtide.v1.InferenceService/GenerateStream": EndpointSync.server_stream(
                    method=MethodInfo(
                        name="GenerateStream",
                        service_name="kvtide.v1.InferenceService",
                        input=GenerateRequest,
                        output=GenerateResponseChunk,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.generate_stream,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/kvtide.v1.InferenceService"


class InferenceServiceClientSync(ConnectClientSync):
    def __init__(
        self,
        address: str,
        *,
        codec: Codec | None = _PROTO_BINARY_CODEC,
        protocol: ProtocolType = ProtocolType.CONNECT,
        accept_compression: Iterable[Compression] | None = None,
        send_compression: Compression | None = _GZIP_COMPRESSION,
        timeout_ms: int | None = None,
        read_max_bytes: int | None = None,
        interceptors: Iterable[InterceptorSync] = (),
        http_client: SyncClient | None = None,
    ) -> None:
        super().__init__(
            address=address,
            codec=codec,
            protocol=protocol,
            accept_compression=accept_compression,
            send_compression=send_compression,
            timeout_ms=timeout_ms,
            read_max_bytes=read_max_bytes,
            interceptors=interceptors,
            http_client=http_client,
        )
    def generate(
        self,
        request: GenerateRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> GenerateResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Generate",
                service_name="kvtide.v1.InferenceService",
                input=GenerateRequest,
                output=GenerateResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def generate_stream(
        self,
        request: GenerateRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> Iterator[GenerateResponseChunk]:
        return self.execute_server_stream(
            request=request,
            method=MethodInfo(
                name="GenerateStream",
                service_name="kvtide.v1.InferenceService",
                input=GenerateRequest,
                output=GenerateResponseChunk,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
class AdminService(Protocol):
    async def health(self, request: HealthRequest, ctx: RequestContext[HealthRequest, HealthResponse]) -> HealthResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def get_runtime_stats(self, request: GetRuntimeStatsRequest, ctx: RequestContext[GetRuntimeStatsRequest, GetRuntimeStatsResponse]) -> GetRuntimeStatsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def get_executors(self, request: GetExecutorsRequest, ctx: RequestContext[GetExecutorsRequest, GetExecutorsResponse]) -> GetExecutorsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class AdminServiceASGIApplication(ConnectASGIApplication[AdminService]):
    def __init__(
        self,
        service: AdminService | AsyncGenerator[AdminService],
        *,
        interceptors: Iterable[Interceptor] = (),
        read_max_bytes: int | None = None,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = _DEFAULT_CODECS,
    ) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/kvtide.v1.AdminService/Health": Endpoint.unary(
                    method=MethodInfo(
                        name="Health",
                        service_name="kvtide.v1.AdminService",
                        input=HealthRequest,
                        output=HealthResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.health,
                ),
                "/kvtide.v1.AdminService/GetRuntimeStats": Endpoint.unary(
                    method=MethodInfo(
                        name="GetRuntimeStats",
                        service_name="kvtide.v1.AdminService",
                        input=GetRuntimeStatsRequest,
                        output=GetRuntimeStatsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_runtime_stats,
                ),
                "/kvtide.v1.AdminService/GetExecutors": Endpoint.unary(
                    method=MethodInfo(
                        name="GetExecutors",
                        service_name="kvtide.v1.AdminService",
                        input=GetExecutorsRequest,
                        output=GetExecutorsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_executors,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/kvtide.v1.AdminService"


class AdminServiceClient(ConnectClient):
    def __init__(
        self,
        address: str,
        *,
        codec: Codec | None = _PROTO_BINARY_CODEC,
        protocol: ProtocolType = ProtocolType.CONNECT,
        accept_compression: Iterable[Compression] | None = None,
        send_compression: Compression | None = _GZIP_COMPRESSION,
        timeout_ms: int | None = None,
        read_max_bytes: int | None = None,
        interceptors: Iterable[Interceptor] = (),
        http_client: Client | None = None,
    ) -> None:
        super().__init__(
            address=address,
            codec=codec,
            protocol=protocol,
            accept_compression=accept_compression,
            send_compression=send_compression,
            timeout_ms=timeout_ms,
            read_max_bytes=read_max_bytes,
            interceptors=interceptors,
            http_client=http_client,
        )
    async def health(
        self,
        request: HealthRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> HealthResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Health",
                service_name="kvtide.v1.AdminService",
                input=HealthRequest,
                output=HealthResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_runtime_stats(
        self,
        request: GetRuntimeStatsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> GetRuntimeStatsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetRuntimeStats",
                service_name="kvtide.v1.AdminService",
                input=GetRuntimeStatsRequest,
                output=GetRuntimeStatsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_executors(
        self,
        request: GetExecutorsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> GetExecutorsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetExecutors",
                service_name="kvtide.v1.AdminService",
                input=GetExecutorsRequest,
                output=GetExecutorsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

class AdminServiceSync(Protocol):
    def health(self, request: HealthRequest, ctx: RequestContext[HealthRequest, HealthResponse]) -> HealthResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def get_runtime_stats(self, request: GetRuntimeStatsRequest, ctx: RequestContext[GetRuntimeStatsRequest, GetRuntimeStatsResponse]) -> GetRuntimeStatsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def get_executors(self, request: GetExecutorsRequest, ctx: RequestContext[GetExecutorsRequest, GetExecutorsResponse]) -> GetExecutorsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class AdminServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(
        self,
        service: AdminServiceSync,
        interceptors: Iterable[InterceptorSync] = (),
        read_max_bytes: int | None = None,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = _DEFAULT_CODECS,
    ) -> None:
        super().__init__(
            endpoints={
                "/kvtide.v1.AdminService/Health": EndpointSync.unary(
                    method=MethodInfo(
                        name="Health",
                        service_name="kvtide.v1.AdminService",
                        input=HealthRequest,
                        output=HealthResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.health,
                ),
                "/kvtide.v1.AdminService/GetRuntimeStats": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetRuntimeStats",
                        service_name="kvtide.v1.AdminService",
                        input=GetRuntimeStatsRequest,
                        output=GetRuntimeStatsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_runtime_stats,
                ),
                "/kvtide.v1.AdminService/GetExecutors": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetExecutors",
                        service_name="kvtide.v1.AdminService",
                        input=GetExecutorsRequest,
                        output=GetExecutorsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_executors,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/kvtide.v1.AdminService"


class AdminServiceClientSync(ConnectClientSync):
    def __init__(
        self,
        address: str,
        *,
        codec: Codec | None = _PROTO_BINARY_CODEC,
        protocol: ProtocolType = ProtocolType.CONNECT,
        accept_compression: Iterable[Compression] | None = None,
        send_compression: Compression | None = _GZIP_COMPRESSION,
        timeout_ms: int | None = None,
        read_max_bytes: int | None = None,
        interceptors: Iterable[InterceptorSync] = (),
        http_client: SyncClient | None = None,
    ) -> None:
        super().__init__(
            address=address,
            codec=codec,
            protocol=protocol,
            accept_compression=accept_compression,
            send_compression=send_compression,
            timeout_ms=timeout_ms,
            read_max_bytes=read_max_bytes,
            interceptors=interceptors,
            http_client=http_client,
        )
    def health(
        self,
        request: HealthRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> HealthResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Health",
                service_name="kvtide.v1.AdminService",
                input=HealthRequest,
                output=HealthResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def get_runtime_stats(
        self,
        request: GetRuntimeStatsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> GetRuntimeStatsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetRuntimeStats",
                service_name="kvtide.v1.AdminService",
                input=GetRuntimeStatsRequest,
                output=GetRuntimeStatsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def get_executors(
        self,
        request: GetExecutorsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> GetExecutorsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetExecutors",
                service_name="kvtide.v1.AdminService",
                input=GetExecutorsRequest,
                output=GetExecutorsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
