networks:
  mini-llm:
    name: mini-llm
    driver: bridge

services:
  executor:
    container_name: executor
    build:
      context: .
      dockerfile: docker/executor.Dockerfile
    image: mini-llm-executor:local
    expose:
      - "19991"
    volumes:
      - ./llm_serve/models/Qwen3-0.6B:/app/models/Qwen3-0.6B:ro
    networks:
      - mini-llm

  server:
    container_name: server
    build:
      context: .
      dockerfile: docker/server.Dockerfile
    image: mini-llm-server:local
    command:
      - --conf=/etc/mini-llm/server.toml
    depends_on:
      - executor
    ports:
      - "8800:8800"
      - "8801:8801"
    volumes:
      - ./config/compose-server.toml:/etc/mini-llm/server.toml:ro
      - ./llm_serve/models/Qwen3-0.6B:/models/Qwen3-0.6B:ro
    networks:
      - mini-llm

  web:
    container_name: web
    build:
      context: .
      dockerfile: docker/web.Dockerfile
    image: mini-llm-web:local
    depends_on:
      - server
    ports:
      - "5173:5173"
    networks:
      - mini-llm
