# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: kvtide/v1/executor.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.codec import Codec
from connectrpc.compression import Compression
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import kvtide.v1.executor_pb2 as kvtide_dot_v1_dot_executor__pb2


class ExecutorService(Protocol):
    async def get_runtime(self, request: kvtide_dot_v1_dot_executor__pb2.GetRuntimeRequest, ctx: RequestContext) -> kvtide_dot_v1_dot_executor__pb2.GetRuntimeResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def execute_batch(self, request: kvtide_dot_v1_dot_executor__pb2.ExecuteBatchRequest, ctx: RequestContext) -> kvtide_dot_v1_dot_executor__pb2.ExecuteBatchResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def release_blocks(self, request: kvtide_dot_v1_dot_executor__pb2.ReleaseBlocksRequest, ctx: RequestContext) -> kvtide_dot_v1_dot_executor__pb2.ReleaseBlocksResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class ExecutorServiceASGIApplication(ConnectASGIApplication[ExecutorService]):
    def __init__(self, service: ExecutorService | AsyncGenerator[ExecutorService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/kvtide.v1.ExecutorService/GetRuntime": Endpoint.unary(
                    method=MethodInfo(
                        name="GetRuntime",
                        service_name="kvtide.v1.ExecutorService",
                        input=kvtide_dot_v1_dot_executor__pb2.GetRuntimeRequest,
                        output=kvtide_dot_v1_dot_executor__pb2.GetRuntimeResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_runtime,
                ),
                "/kvtide.v1.ExecutorService/ExecuteBatch": Endpoint.unary(
                    method=MethodInfo(
                        name="ExecuteBatch",
                        service_name="kvtide.v1.ExecutorService",
                        input=kvtide_dot_v1_dot_executor__pb2.ExecuteBatchRequest,
                        output=kvtide_dot_v1_dot_executor__pb2.ExecuteBatchResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.execute_batch,
                ),
                "/kvtide.v1.ExecutorService/ReleaseBlocks": Endpoint.unary(
                    method=MethodInfo(
                        name="ReleaseBlocks",
                        service_name="kvtide.v1.ExecutorService",
                        input=kvtide_dot_v1_dot_executor__pb2.ReleaseBlocksRequest,
                        output=kvtide_dot_v1_dot_executor__pb2.ReleaseBlocksResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.release_blocks,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/kvtide.v1.ExecutorService"


class ExecutorServiceClient(ConnectClient):
    async def get_runtime(
        self,
        request: kvtide_dot_v1_dot_executor__pb2.GetRuntimeRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> kvtide_dot_v1_dot_executor__pb2.GetRuntimeResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetRuntime",
                service_name="kvtide.v1.ExecutorService",
                input=kvtide_dot_v1_dot_executor__pb2.GetRuntimeRequest,
                output=kvtide_dot_v1_dot_executor__pb2.GetRuntimeResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def execute_batch(
        self,
        request: kvtide_dot_v1_dot_executor__pb2.ExecuteBatchRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> kvtide_dot_v1_dot_executor__pb2.ExecuteBatchResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ExecuteBatch",
                service_name="kvtide.v1.ExecutorService",
                input=kvtide_dot_v1_dot_executor__pb2.ExecuteBatchRequest,
                output=kvtide_dot_v1_dot_executor__pb2.ExecuteBatchResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def release_blocks(
        self,
        request: kvtide_dot_v1_dot_executor__pb2.ReleaseBlocksRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> kvtide_dot_v1_dot_executor__pb2.ReleaseBlocksResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ReleaseBlocks",
                service_name="kvtide.v1.ExecutorService",
                input=kvtide_dot_v1_dot_executor__pb2.ReleaseBlocksRequest,
                output=kvtide_dot_v1_dot_executor__pb2.ReleaseBlocksResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )





class ExecutorServiceSync(Protocol):
    def get_runtime(self, request: kvtide_dot_v1_dot_executor__pb2.GetRuntimeRequest, ctx: RequestContext) -> kvtide_dot_v1_dot_executor__pb2.GetRuntimeResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def execute_batch(self, request: kvtide_dot_v1_dot_executor__pb2.ExecuteBatchRequest, ctx: RequestContext) -> kvtide_dot_v1_dot_executor__pb2.ExecuteBatchResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def release_blocks(self, request: kvtide_dot_v1_dot_executor__pb2.ReleaseBlocksRequest, ctx: RequestContext) -> kvtide_dot_v1_dot_executor__pb2.ReleaseBlocksResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class ExecutorServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: ExecutorServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            endpoints={
                "/kvtide.v1.ExecutorService/GetRuntime": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetRuntime",
                        service_name="kvtide.v1.ExecutorService",
                        input=kvtide_dot_v1_dot_executor__pb2.GetRuntimeRequest,
                        output=kvtide_dot_v1_dot_executor__pb2.GetRuntimeResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_runtime,
                ),
                "/kvtide.v1.ExecutorService/ExecuteBatch": EndpointSync.unary(
                    method=MethodInfo(
                        name="ExecuteBatch",
                        service_name="kvtide.v1.ExecutorService",
                        input=kvtide_dot_v1_dot_executor__pb2.ExecuteBatchRequest,
                        output=kvtide_dot_v1_dot_executor__pb2.ExecuteBatchResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.execute_batch,
                ),
                "/kvtide.v1.ExecutorService/ReleaseBlocks": EndpointSync.unary(
                    method=MethodInfo(
                        name="ReleaseBlocks",
                        service_name="kvtide.v1.ExecutorService",
                        input=kvtide_dot_v1_dot_executor__pb2.ReleaseBlocksRequest,
                        output=kvtide_dot_v1_dot_executor__pb2.ReleaseBlocksResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.release_blocks,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/kvtide.v1.ExecutorService"


class ExecutorServiceClientSync(ConnectClientSync):
    def get_runtime(
        self,
        request: kvtide_dot_v1_dot_executor__pb2.GetRuntimeRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> kvtide_dot_v1_dot_executor__pb2.GetRuntimeResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetRuntime",
                service_name="kvtide.v1.ExecutorService",
                input=kvtide_dot_v1_dot_executor__pb2.GetRuntimeRequest,
                output=kvtide_dot_v1_dot_executor__pb2.GetRuntimeResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def execute_batch(
        self,
        request: kvtide_dot_v1_dot_executor__pb2.ExecuteBatchRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> kvtide_dot_v1_dot_executor__pb2.ExecuteBatchResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ExecuteBatch",
                service_name="kvtide.v1.ExecutorService",
                input=kvtide_dot_v1_dot_executor__pb2.ExecuteBatchRequest,
                output=kvtide_dot_v1_dot_executor__pb2.ExecuteBatchResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def release_blocks(
        self,
        request: kvtide_dot_v1_dot_executor__pb2.ReleaseBlocksRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> kvtide_dot_v1_dot_executor__pb2.ReleaseBlocksResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ReleaseBlocks",
                service_name="kvtide.v1.ExecutorService",
                input=kvtide_dot_v1_dot_executor__pb2.ReleaseBlocksRequest,
                output=kvtide_dot_v1_dot_executor__pb2.ReleaseBlocksResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


