[server]
address = "0.0.0.0:8800"
adminPort = 8801
allowedOrigins = [
  "http://localhost:5173",
  "http://127.0.0.1:5173",
]

[server.scheduleConf]
maxBatchSeqs = 32
maxBatchTokens = 2048
longPrefillTokenThreshold = 512
maxPartialPrefills = 2
maxLongPartialPrefills = 1
maxScheduleDelay = 10 # ms

[server.scheduleConf.queueConf]
queueLength = 100

[[models]]
modelId = "Qwen/Qwen3-0.6B"
modelPath = "/models/Qwen3-0.6B"

[[executors]]
id = "executor-qwen3-0.6B"
modelId = "Qwen/Qwen3-0.6B"
address = ["http://executor:19991"]
timeoutMs = 120000
