# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mini_llm_serve/v1/block.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'mini_llm_serve/v1/block.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dmini_llm_serve/v1/block.proto\x12\x11mini_llm_serve.v1\"|\n\x0fKVBlockMetadata\x12\x1d\n\nblock_size\x18\x01 \x01(\rR\tblockSize\x12\x1f\n\x0b\x62lock_table\x18\x02 \x03(\rR\nblockTable\x12)\n\x10\x61llocated_blocks\x18\x03 \x03(\rR\x0f\x61llocatedBlocksB\xcf\x01\n\x15\x63om.mini_llm_serve.v1B\nBlockProtoP\x01ZMgithub.com/qujing226/mini-llm-serve/gen/go/mini_llm_serve/v1;mini_llm_servev1\xa2\x02\x03MXX\xaa\x02\x0fMiniLlmServe.V1\xca\x02\x0fMiniLlmServe\\V1\xe2\x02\x1bMiniLlmServe\\V1\\GPBMetadata\xea\x02\x10MiniLlmServe::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mini_llm_serve.v1.block_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\025com.mini_llm_serve.v1B\nBlockProtoP\001ZMgithub.com/qujing226/mini-llm-serve/gen/go/mini_llm_serve/v1;mini_llm_servev1\242\002\003MXX\252\002\017MiniLlmServe.V1\312\002\017MiniLlmServe\\V1\342\002\033MiniLlmServe\\V1\\GPBMetadata\352\002\020MiniLlmServe::V1'
  _globals['_KVBLOCKMETADATA']._serialized_start=52
  _globals['_KVBLOCKMETADATA']._serialized_end=176
# @@protoc_insertion_point(module_scope)
