# Deployment 属于 apps group，所以写 apps/v1
apiVersion: apps/v1
kind: Deployment

metadata:
  name: executor
  namespace: kvtide

spec:
  # 1 个运行 executor container 的 Pod
  replicas: 1

  selector:
    # Deployment 用该标签识别自己管理的 Pod。
    matchLabels:
      app: executor

  # Pod 模板，ReplicaSet 根据它创建 Pod。
  template:
    metadata:
      # 必须匹配 selector 中的 Label
      labels:
        app: executor

    spec:
      # 每个 Pod 中运行的容器列表
      containers:
        - name: executor
          image: kvtide-executor:local
          imagePullPolicy: IfNotPresent

          ports:
            - name: rpc
              containerPort: 19991

          # kubelet 定期尝试连接容器的 rpc 端口。
          # 成功：Pod 显式 1/1 Ready，可以加入 Service EndpointSlice
          # 失败：Pod 显式 0/1 Running，从 Service 后端移除。
          readinessProbe:
            tcpSocket:
              port: rpc
            # 容器启动两秒后检查
            initialDelaySeconds: 5
            # 每三秒检查一次
            periodSeconds: 3
            # 一次检查最多等待一秒
            timeoutSeconds: 1
            # 连续三次失败判定 NotReady
            failureThreshold: 3

          # 连接 rpc 端口，失败三次将重启容器，用于处理 “进程还在，但已经无法提供服务”的情况。
          livenessProbe:
            tcpSocket:
              port: rpc
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3

          # Kubernetes QoS 分三类：
          # Guaranteed：所有容器的 CPU/内存 request 等于 limit。
          # Burstable：至少配置了部分 requests/limits，但不满足 Guaranteed。
          # BestEffort：完全没有配置 requests/limits。
          # 内存压力下，通常优先驱逐：
          # BestEffort -> Burstable -> Guaranteed
          resources:
            # Scheduler 做容量核算时，该 Pod 声明需要占用的调度资源。
            requests:
              # 0.1 个CPU核心
              cpu: "100m"
              # 128 MiB内存
              memory: "128Mi"
            # 容器允许使用的资源上限。
            limits:
              cpu: "500m"
              memory: "256Mi"



# 装载镜像
# kind load docker-image kvtide-executor:local --name kvtide

# 应用
# kubectl apply -f k8s/base/executor-deployment.yaml
# 检查
# kubectl get deployments -n kvtide
# kubectl get replicasets -n kvtide
# kubectl get pods -n kvtide -o wide