apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - executor-deployment.yaml
  - executor-service.yaml
  - server-config.yaml
  - server-deployment.yaml
  - server-service.yaml
