apiVersion: v1
kind: ConfigMap

metadata:
  name: server-config
  namespace: kvtide

data:
  server.toml: |
    [server]
    address = "0.0.0.0:8800"
    adminPort = 8801

    [server.scheduleConf]
    maxBatchSeqs = 32
    maxBatchTokens = 2048
    longPrefillTokenThreshold = 512
    maxPartialPrefills = 2
    maxLongPartialPrefills = 1
    maxScheduleDelay = 10

    [server.scheduleConf.queueConf]
    queueLength = 100

    [[models]]
    modelId = "Qwen/Qwen3-0.6B"
    modelPath = "/models/Qwen3-0.6B"

    [[executors]]
    executorId = "executor-qwen3-0.6B"
    address = ["http://executor:19991"]
    timeoutMs = 120000
