apiVersion: v1
kind: Service

metadata:
  name: server
  namespace: kvtide

spec:
  type: ClusterIP
  selector:
    app: server
  ports:
    - name: "server"
      port: 8800
      targetPort: server
    - name: "metrics"
      port: 8801
      targetPort: metrics

# 应用
# kubectl apply -f k8s/base/server-service.yaml
# 验证
# kubectl get services -n kvtide
# kubectl get endpointslices -n kvtide
